server:
  port: 8080
logging:
  level:
    org:
      springframework:
        web: DEBUG
spring:
  datasource:
    driver-class-name: org.h2.Driver
    password: sa
    url: jdbc:h2:file:/Users/genchev/projects/java/noser/vending-machine/src/main/resources/h2_data/vending_machine
    username: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html